server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auction_server?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: sa123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: test

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
