server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/acution_server?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: sa123456
    driver-class-name: com.mysql.cj.jdbc.Driver

    # 福森测试环境
#    url: jdbc:mysql://localhost:3306/Akidb?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379
mybatis:
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  dialect: mysql
  reasonable: false
  support-methods-arguments: true
